### ISSUE TITLE
CUDA kernel failed : no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by HansRen1024** [mkt1412/GraspGPT_public#8]
Hi team, thank you so much for your work. 

I got a problem as the tittle shows. A lot of search work has been done, I eventially found it is an old problem of PointNet2. (see https://github.com/erikwijmans/Pointnet2_PyTorch/issues?q=furthest_point_sampling_kernel_wrapper)

I believe the problem is caused by the version of python, pytorch and CUDA. 

I followed your instruction and tried: 
    1. Python 3.7.1 + torcu 1.11.0 + CUDA 11.3
    2. Python 3.7.9 + torch 1.11.0 + CUDA 11.3
    3. Python 3.7.9 + torch 1.11.0 + CUDA 10.0
but there is no lucky. 

My GPU is 4090.

Please can I ask what specific version of python you used? And if you can advise me of any hint for the problem, it would be much appreciated.

**Comment by HansRen1024** [comment]
The problem is solved, here is the solution:

Comment out all  "CUDA_CHECK_ERRORS();" in .cu files in "_ext-src/src/" in PointNet2 project.

**Comment by yu3jun** [comment]
After Comment out all "CUDA_CHECK_ERRORS(), you should reinstall the setup.py in PointNetpp, otherwise the the modification will not take effect.

**Comment by bruce2233** [comment]
It helps， Thansk a lot
